version: '3.8'
services:
  cache-db:
    image: redis:6.2-alpine
    container_name: DEV_REDIS
    restart: alwaysit
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass kevingeogarcia
